Resources:
  userTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: password
          AttributeType: S
        - AttributeName: datetime
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
        - AttributeName: password
          KeyType: RANGE
        - AttributeName: datetime
          KeyType: RANGE
        - AttributeName: email
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
