AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for getFact endpoint

Parameters:
  LambdaDeploymentBucketName:
    Type: String
    Description: Name of the S3 bucket for Lambda deployments
  LambdaCodeKey:
    Type: String
    Description: S3 key for the Lambda deployment package

Resources:
  GetFactLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: get-fact-lambda
      Handler: src/handlers/fact.getFact
      Role: !GetAtt LambdaCognitoBedrockAccessRole.Arn
      Runtime: python3.9
      Timeout: 5
      MemorySize: 128
      Code:
        S3Bucket: !Ref LambdaDeploymentBucketName
        S3Key: !Ref LambdaCodeKey
