AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Lambda with access to query Bedrock and authenticate with Cognito

Resources:
  LambdaCognitoBedrockAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: super-app-lambda-cognito-bedrock-access
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CognitoAndBedrockAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminRespondToAuthChallenge
                Resource: '*'
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
Outputs:
  LambdaCognitoBedrockAccessRoleArn:
    Description: IAM Role ARN for Lambda Cognito and Bedrock Access
    Value: !GetAtt LambdaCognitoBedrockAccessRole.Arn
