AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Deployment S3 Bucket

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to deploy Lambda function code

Resources:
  LambdaDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LambdaDeploymentBucketName:
    Description: Name of the S3 bucket for Lambda deployments
    Value: !Ref LambdaDeploymentBucket
  LambdaDeploymentBucketArn:
    Description: ARN of the S3 bucket for Lambda deployments
    Value: !GetAtt LambdaDeploymentBucket.Arn
