service: super-app-serverless

provider:
  name: aws
  stage: dev
  region: us-east-2
  stackName: super-app-serverless-${sls:stage}
  runtime: nodejs14.x
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!node_modules'
    - '!.git/**'
  individually: true
  excludeDevDependencies: false

plugins:
  - serverless-bundle
  - serverless-plugin-bind-deployment-id

functions:
  login:
    handler: src/lambdas/user.login
    events:
      - httpApi: 'POST /super-app/login'
  register:
    handler: src/lambdas/user.register
    events:
      - httpApi: 'POST /super-app/register'

resources:
  - ${file(serverless-resources/dynamo.yml)}
  - ${file(serverless-resources/api-gateway.yml)}
  - ${file(serverless-resources/iam.yml)}
  - ${file(serverless-resources/cloudwatch.yml)}
