service: super-app-serverless

provider:
  name: aws
  stage: dev
  region: us-east-2
  stackName: ${self:service}-${sls:stage}-stack
  runtime: nodejs14.x

package:
  patterns:
    - '!node_modules'
    - '!.git/**'
  individually: true
  excludeDevDependencies: false

plugins:
  - serverless-bundle
  - serverless-plugin-bind-deployment-id

functions:
  login:
    handler: src/lambdas/user.login
    events:
      - httpApi: 'POST /super-app/login'
    role: LambdaExecutionRole
  register:
    handler: src/lambdas/user.register
    events:
      - httpApi: 'POST /super-app/register'
    role: LambdaExecutionRole

resources:
  - ${file(serverless-resources/dynamo.yml)}
  - ${file(serverless-resources/api-gateway.yml)}
  - ${file(serverless-resources/iam.yml)}
  - ${file(serverless-resources/cloudwatch.yml)}
